---
- name: "MEALIE | Ensure mealie is running"
  ansible.builtin.command:
    cmd: "docker compose -f {{ mealie_config_path | expanduser | realpath }}/docker-compose.yml -d up"
  tags:
    - mealie_install
