---
dependency:
  name: galaxy
  options:
    ignore-certs: true
    ignore-errors: true
    role-file: molecule/requirements.yml
    requirements-file: molecule/requirements.yml
driver:
  name: docker
lint: |
  yamllint .
  ansible-lint .
platforms:
  - name: mealie
    groups:
      - mealie_group
    image: "geerlingguy/docker-${MOLECULE_DISTRO:-centos8}-ansible:latest"
    privileged: true
    pre_build_image: true
    capabilities:
      - SYS_ADMIN
    tmpfs:
      - /tmp
      - /run
      - /run/lock
    volumes:
      - '/sys/fs/cgroup:/sys/fs/cgroup:ro'
      - '/var/run/docker.sock:/tmp/docker_mounted.sock'
    command: '/lib/systemd/systemd'
    stop_signal: 'RTMIN+3'
provisioner:
  name: ansible
  playbooks:
    converge: ${MOLECULE_PLAYBOOK:-converge.yml}
verifier:
  name: ansible

